// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewsWebAPI.Models;

public partial class Role
{
    public Guid EmployeesId { get; set; }

    public string Role1 { get; set; }
}