// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewsWebAPI.Models;

public partial class Employee
{
    public Guid EmployeesId { get; set; }

    public string Name { get; set; }

    public Guid JobId { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }
}